/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Java library project to get you started.
 * For more details on building Java & JVM projects, please refer to https://docs.gradle.org/8.9/userguide/building_java_projects.html in the Gradle documentation.
 * This project uses @Incubating APIs which are subject to change.
 */

plugins {
    // Apply the java-library plugin for API and implementation separation.
    // `java-library`
    // application
    id("java")
    id("war")
    
}

repositories {
    // Use Maven Central for resolving dependencies.
    mavenCentral()
}

dependencies {
    //  implementation("org.apache.commons:commons-math3:3.6.1") // replace with your actual dependency
    // implementation("com.google.guava:guava:31.1-jre") // replace with your actual dependency
    implementation("javax.servlet:javax.servlet-api:4.0.1")
}

testing {
    suites {
        // Configure the built-in test suite
        val test by getting(JvmTestSuite::class) {
            // Use JUnit4 test framework
            useJUnit("4.13.2")
        }
    }
}

// Apply a specific Java toolchain to ease working on different environments.
java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}

// tasks.war {
//     webAppDirName = "src/main/webapp"
// }

// war {
//     from("src/main/webapp"){
//         include("**/*.jsp")
//     }
// }
